const Data_Alphabet = [
  {
    id: 1,
    letter: "a",
    img_src: require("../images/letters/a.png"),
    sound_src: require("../sounds/pronounce/a.mp3"),
  },
  {
    id: 2,
    letter: "b",
    img_src: require("../images/letters/b.png"),
    sound_src: require("../sounds/pronounce/b.mp3"),
  },
  {
    id: 3,
    letter: "c",
    img_src: require("../images/letters/c.png"),
    sound_src: require("../sounds/pronounce/c.mp3"),
  },
  {
    id: 4,
    letter: "d",
    img_src: require("../images/letters/d.png"),
    sound_src: require("../sounds/pronounce/d.mp3"),
  },
  {
    id: 5,
    letter: "e",
    img_src: require("../images/letters/e.png"),
    sound_src: require("../sounds/pronounce/e.mp3"),
  },
  {
    id: 6,
    letter: "f",
    img_src: require("../images/letters/f.png"),
    sound_src: require("../sounds/pronounce/f.mp3"),
  },
  {
    id: 7,
    letter: "g",
    img_src: require("../images/letters/g.png"),
    sound_src: require("../sounds/pronounce/g.mp3"),
  },
  {
    id: 8,
    letter: "h",
    img_src: require("../images/letters/h.png"),
    sound_src: require("../sounds/pronounce/h.mp3"),
  },
  {
    id: 9,
    letter: "i",
    img_src: require("../images/letters/i.png"),
    sound_src: require("../sounds/pronounce/i.mp3"),
  },
  {
    id: 10,
    letter: "j",
    img_src: require("../images/letters/j.png"),
    sound_src: require("../sounds/pronounce/j.mp3"),
  },
  {
    id: 11,
    letter: "k",
    img_src: require("../images/letters/k.png"),
    sound_src: require("../sounds/pronounce/k.mp3"),
  },
  {
    id: 12,
    letter: "l",
    img_src: require("../images/letters/l.png"),
    sound_src: require("../sounds/pronounce/l.mp3"),
  },
  {
    id: 13,
    letter: "m",
    img_src: require("../images/letters/m.png"),
    sound_src: require("../sounds/pronounce/m.mp3"),
  },
  {
    id: 14,
    letter: "n",
    img_src: require("../images/letters/n.png"),
    sound_src: require("../sounds/pronounce/n.mp3"),
  },
  {
    id: 15,
    letter: "o",
    img_src: require("../images/letters/o.png"),
    sound_src: require("../sounds/pronounce/o.mp3"),
  },
  {
    id: 16,
    letter: "p",
    img_src: require("../images/letters/p.png"),
    sound_src: require("../sounds/pronounce/p.mp3"),
  },
  {
    id: 17,
    letter: "q",
    img_src: require("../images/letters/q.png"),
    sound_src: require("../sounds/pronounce/q.mp3"),
  },
  {
    id: 18,
    letter: "r",
    img_src: require("../images/letters/r.png"),
    sound_src: require("../sounds/pronounce/r.mp3"),
  },
  {
    id: 19,
    letter: "s",
    img_src: require("../images/letters/s.png"),
    sound_src: require("../sounds/pronounce/s.mp3"),
  },
  {
    id: 20,
    letter: "t",
    img_src: require("../images/letters/t.png"),
    sound_src: require("../sounds/pronounce/t.mp3"),
  },
  {
    id: 21,
    letter: "u",
    img_src: require("../images/letters/u.png"),
    sound_src: require("../sounds/pronounce/u.mp3"),
  },
  {
    id: 22,
    letter: "v",
    img_src: require("../images/letters/v.png"),
    sound_src: require("../sounds/pronounce/v.mp3"),
  },
  {
    id: 23,
    letter: "w",
    img_src: require("../images/letters/w.png"),
    sound_src: require("../sounds/pronounce/w.mp3"),
  },
  {
    id: 24,
    letter: "x",
    img_src: require("../images/letters/x.png"),
    sound_src: require("../sounds/pronounce/x.mp3"),
  },
  {
    id: 25,
    letter: "y",
    img_src: require("../images/letters/y.png"),
    sound_src: require("../sounds/pronounce/y.mp3"),
  },
  {
    id: 26,
    letter: "z",
    img_src: require("../images/letters/z.png"),
    sound_src: require("../sounds/pronounce/z.mp3"),
  },
];

export default Data_Alphabet;
